spring.application.name=alunos-service

# Datasource
spring.datasource.url=jdbc:postgresql://postgres-jdbc-1991cf093d4-10bd7b4985c814d7:5432/NOME_DO_SEU_BANCO?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=1201
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true